### ISSUE TITLE
Users Add bug

### ISSUE THREAD

**Issue by VicentGJ** [VicentGJ/AD-webmanager#10]
Users are not being created in the proper OUs, instead are created in the root

**Comment by aleadco** [comment]
En la mañana puede crear dos cuentas, este error apareció después.

![image](https://user-images.githubusercontent.com/35962168/103695897-659fd280-4f6b-11eb-89e6-745bc2e03ffd.png)

**Comment by VicentGJ** [comment]
Ok, I got it.
It seems to be related to UserAdd.base not being reset after creating a user.
Seems to be fixed now, needs more testing before closing the issue.

**Comment by aleadco** [comment]
> Ok, I got it.
> It seems to be related to UserAdd.base not being reset after creating a user.
> Seems to be fixed now, needs more testing before closing the issue.

Se mantiene el error.

![20210105_192814.jpg](https://user-images.githubusercontent.com/35962168/103714278-45344000-4f8c-11eb-8cac-b415a06ba806.jpg)

**Comment by VicentGJ** [comment]
No puedo reproducir tu problema, prueba cerrar navegador y limpiar cache

**Comment by aleadco** [comment]
Cambie de navegador, de igual forma obtengo el error.
Fíjate que cada imagen que te adjunto es probando con un usuario diferente.

![image](https://user-images.githubusercontent.com/35962168/103819856-3eafd200-5039-11eb-8adf-6a59fa4c55ef.png)

**Comment by VicentGJ** [comment]
Cogí tu usuario y lo usé para crear un usuario, no tuve problemas, hay algun problema con tus navegadores. Cambie tu contraseña para cujae2019*
![image](https://user-images.githubusercontent.com/52976500/103836492-3e263400-5057-11eb-9e77-6e247ef8e5f8.png)

**Comment by aleadco** [comment]
Tercera PC y nuevo navegador con los que pruebo y nuevo error.

![20210107_193446.jpg](https://user-images.githubusercontent.com/35962168/103960362-f9b29b00-511f-11eb-8666-1b227c1e4497.jpg)

**Comment by aleadco** [comment]
El problema está relacionado con la Categoría.
Si seleccionas la Categoría Sin Internet no puedes obtiene el error anterior.
Destaco que no es un problema de caché ni de navegadores.
 Por favor reabre el problema.

**Comment by aleadco** [comment]
Elimine el usuario soporte para volver a probar y resulta lo siguiente.

![20210107_202902.jpg](https://user-images.githubusercontent.com/35962168/103963393-261de580-5127-11eb-9581-c49d61500ae3.jpg)

**Comment by aleadco** [comment]
No logro definir que factor está incidiendo en estos errores. Actualmente ya he creado 3 cuentas de administración usando la Categoría A.
