### ISSUE TITLE
Adicionar usuarios de otras OU a grupos o listas de distribución..

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#11]
Es necesario que, conociendo previamente el usuario, pueda adicionarlo a mis grupos o listas de distribución. Actualmente solo elo puedo hacer con los siguientes usuario que probé (acivan, acarturo) puesto que seguro tienen algún tipo de permiso en el AD, pero de forma general debería de poder hacerlo con cualquiera dada la necesidad de que los usuarios de un área puedan acceder a los servicios de otras.

Teniendo la posibilidad de visualizar un usuario de otra OU cuando realice una búsqueda directa como hice con esos usuarios es suficiente para resolver esta cuestión.

**Comment by VicentGJ** [comment]
Resolver este problema requiere de una sustancial modificación a los permisos establecidos en el Directorio, llevar esto acabo debería llevar seria discusión.
Cerrando porque no es relevante para Webmanager.
