### ISSUE TITLE
Aumentar tiempos de espera del proxy inverso del servicio

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#12]
Cuando intentas agregar por lotes de más de 50 usuarios el tiempo de espera de solicitud de servicios web es demasiando bajo como para completar la solicitud por lo que se obtiene el siguiente error

![image](https://user-images.githubusercontent.com/35962168/103706502-de5a5b00-4f7a-11eb-952b-af3b5a280d25.png)

**Comment by VicentGJ** [comment]
Closing this issue, it's not relevant because that feature is not supported, or planned to, in the current version.
#15 opened for keeping track of this request.
