### ISSUE TITLE
El estado "La contraseña expiróno" funciona

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#13]
Establecer la Bandera **La contraseña expiró** no funciona.

![20210105_195137.jpg](https://user-images.githubusercontent.com/35962168/103716117-3cde0400-4f90-11eb-96f2-6b4680f0e11e.jpg)

**Comment by VicentGJ** [comment]
Esa bandera no hace lo que crees, no tenemos manera de comprobar si funciona porque solo es valida para aplicaciones que utilicen directamente el protocolo de autenticación de AD.
Cerrando este Issue hasta que sea relevante.
