### ISSUE TITLE
Add more values to the search

### ISSUE THREAD

**Issue by VicentGJ** [VicentGJ/AD-webmanager#18]
Adicionar los valores de cUJAEDataProvider, cUJAEPersonType, whenCreated, whenCreated, whenChanged

**Comment by aleadco** [comment]
Adicionar Año de Estudios y el Grupo de Estudio.

**Comment by VicentGJ** [comment]
Usa enter para ingresar varios usuarios.

**Comment by VicentGJ** [comment]
Done!!
