### ISSUE TITLE
Roto adicionar usuarios al grupo.

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#21]
Este problema estaba solucionado parcialmente. De forma sencilla, un usuario por línea, podía adicionar múltiples usuarios al grupo sin contar los problemas mencionados en #12 y #15.

Ahora ya no se puede ejecutar tal acción, ni tan siquiera 2 usuarios. Tampoco se puede poner por línea como se hizo anteriormente.

Se probó poniendo coma distintos separadores sin obtener resultados positivos.

![20210109_174530.jpg](https://user-images.githubusercontent.com/35962168/104110557-d0704700-52a6-11eb-80cd-f4e2c1d93018.jpg)

**Comment by VicentGJ** [comment]
Usa enter para separar los usuarios cuando quieras intruducir varios.
