### ISSUE TITLE
Preestablecer checkbox de Cuenta Manual

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#7]
El checkbox de Cuenta Manual debe estar establecido por defecto teniendo en cuenta que el proceso de creación de cuentas por lo general se hará manual y es necesario evitar pasos innecesarios que pueden conllevar a un problema si se pasa por alto este parámetro sin darse cuenta.

![Usuario Manual](https://user-images.githubusercontent.com/35962168/103599583-756bd800-4ed3-11eb-81bd-bb8356fd3570.png)

**Comment by VicentGJ** [comment]
It seems like the current version of wtf-forms has some limitation that does not make this possible.
I mark it as required instead:
![image](https://user-images.githubusercontent.com/52976500/103724622-c4347300-4fa2-11eb-8d25-ed9735e4590d.png)
