### ISSUE TITLE
Mejorar expresión literal de Tipo de Persona y adicionar un parámetro de selección condicionado

### ISSUE THREAD

**Issue by aleadco** [VicentGJ/AD-webmanager#8]
El texto **tipo de persona** debe ser denominado como algo más genérico como por ejemplo **tipo de cuenta**. En este sentido se debe agregar a los valores de selección un parámetro adicional denominado **administrativo** teniendo en cuenta que es una de los objetivos para los cuales se crearía una cuenta manual.

Este valor Administrativo que propongo tiene como fin que se cree, de ser posible, que la variable carnet de identidad sea condicionada si selecciona cualquiera de las dos opciones anteriores, ya sea estudiante o profesor. Por qué digo esto, pues cuando se crean este tipo de cuentas adicionales como VDD, VDEA, etc.. no están asociadas a un carnet y no sería nada bueno dejar ese parámetro a la improvisación para evitar datos falsos ni repetitivos en el sistema.

Es decir que el campo carnet de identidad solo sea obligatorio cuando se crean cuentas de usuarios personales.

![Tipo de Cuenta](https://user-images.githubusercontent.com/35962168/103599990-5de11f00-4ed4-11eb-8b56-a3cda41da1ea.png)

**Comment by VicentGJ** [comment]
Esas dos variables lamentablemente representan de manera literal campos que existen de forma obligatoria en el Directorio, se decidió mostrarlos por simplicidad, no esconder churre del diseño del esquema LDAP, que se viera reflejado tal cual en los campos de edición. Eso facilita muchísimo el mantenimiento del software a pesar de sacrificar usabilidad y experiencia de usuario pero, debido a que es un software dirigido a usuarios con conocimiento, se decidió que era un sacrificio válido.

**Comment by VicentGJ** [comment]
Dejo el reporte abierto para poder continuar la discusión o si se decide que se puede arreglar en un futuro.

**Comment by aleadco** [comment]
Este reporte se puede cerrar. Solo propongo a raíz de lo que conversamos, que pudiéramos agregar una descripción para el administrador que aclare que en caso de que la cuenta que se está creando es administrativa  poner como carnet de identidad 00000000000 para estandarizar el proceso.
