### ISSUE TITLE
Computer object deactivate bug

### ISSUE THREAD

**Issue by mosheg91** [VicentGJ/AD-webmanager#99]
Hi

Looks like there is a bug when deactivating a computer object. It shows as "Active" although it's deactivated. I confirmed with RSAT that the object is Deactivated.

I attached screenshots

Can you please fix it?

Thanks

![Screenshot 2023-02-16 at 15 09 07](https://user-images.githubusercontent.com/111742628/219374275-2cf2de58-d8f6-4f12-8bd6-8c4c9340946e.png)
![Screenshot 2023-02-16 at 15 08 04](https://user-images.githubusercontent.com/111742628/219374281-629a8c9b-2105-4f7a-bb97-5b3e5c7ee327.png)

**Comment by VicentGJ** [comment]
Thanks for pointing this out, I will have a fix soon.

**Comment by mosheg91** [comment]
> Thanks for pointing this out, I will have a fix soon.

Thanks! Much appreciated!

**Comment by VicentGJ** [comment]
The master branch is now updated with a change that should have fixed the issue. It was a bug that was affecting the status of all types of accounts in the tree view (not just computers). Unfortunately, I don't have many computer objects in my domain so I could not test your specific use case extensively. If you find your problem persists, or another related issue comes up, feel free to reopen this issue.
Also, I find out that the support for managing computer objects all around is lacking, so I made an issue specific to improve it #101

**Comment by mosheg91** [comment]
> The master branch is now updated with a change that should have fixed the issue. It was a bug that was affecting the status of all types of accounts in the tree view (not just computers). Unfortunately, I don't have many computer objects in my domain so I could not test your specific use case extensively. If you find your problem persists, or another related issue comes up, feel free to reopen this issue. Also, I find out that the support for managing computer objects all around is lacking, so I made an issue specific to improve it #101

Is there anything I need to do from my end for the update to take effect or just test it?

Thanks for your fast response and willing to fix

**Comment by mosheg91** [comment]
> 

@VicentGJ I replaced the files you modified and I'm now checking if it works.

Will update.

Thanks!

**Comment by bwrgitprotect** [comment]
Hi @VicentGJ

I can confirm all works

Thanks for your prompt help!

**Comment by mosheg91** [comment]
Hi @VicentGJ

I can confirm all works

Thanks for your prompt help!
